defaults: &defaults
  working_directory: ~/code
  docker:
   - image: circleci/node:9
     environment:
       NPM_CONFIG_LOGLEVEL: error # make npm commands less noisy
       JOBS: max # https://gist.github.com/ralphtheninja/f7c45bdee00784b41fed

restore_cache: &restore_cache
  restore_cache:
   keys:
     - code-{{ .Branch }}-{{ checksum ".nvmrc" }}-{{ checksum "package.json" }}

save_cache: &save_cache
  save_cache:
   key: code-{{ .Branch }}-{{ checksum ".nvmrc" }}-{{ checksum "package.json" }}
   paths:
     - node_modules

version: 2
jobs:
  build:
   <<: *defaults
   steps:
     - checkout
     - *restore_cache
     - run: npm install -g npm@latest
     - run: npm ci
     - run: npm install 
     - save_cache: *save_cache
  lint:
   <<: *defaults
   steps:
     - checkout
     - *restore_cache
     - run: npm run lint:ci
  test:
   <<: *defaults
   steps:
     - checkout
     - *restore_cache
     - run: npm run test

workflows:
  - build
  - lint:
      requires: 
        - build
  - test:
      requires: 
        - build