defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/node:9
      environment:
        NPM_CONFIG_LOGLEVEL: error # make npm commands less noisy
        JOBS: max # https://gist.github.com/ralphtheninja/f7c45bdee00784b41fed

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - run: npm ci
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: npm run lint:ci
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm test

workflows:
  version: 2
  all:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build