const qunit = require('node-qunit-phantomjs')

qunit('tests/acceptance/cleanup/index.html')
qunit('tests/acceptance/monitoring/index.html')
qunit('tests/acceptance/multiple/index.html')
qunit('tests/acceptance/multiple-sticky-classes/index.html')
qunit('tests/acceptance/offset/index.html')
qunit('tests/acceptance/scrollTo/index.html')
qunit('tests/acceptance/update/index.html')
qunit('tests/acceptance/use-fixed/index.html')
